# User configuration
plugins=(git)
stty start undef
stty stop undef

# Path to your oh-my-zsh installation.
export EDITOR='vim'

ZSH_THEME="wild-cherry"

# Macbook Pro
alias ajl="cd ~/Sites/artandjustice.development/artandjustice"
alias anthonyleeio="cd ~/Sites/github.pages/antwonlee.github.io"
alias dotfiles="cd ~/Sites/dotfiles"
alias gatech="cd ~/Documents/gatech"
alias js="cd ~/Sites/playgrounds/javascript-playground/"
alias luna="cd ~/Sites/rubyonrails.development/lunamisoo"
alias ml="cd ~/Sites/machinelearning.development/"
alias playground="cd ~/Sites/playground"
alias pluralsight="cd ~/Pluralsight"
alias ror="cd ~/Sites/rubyonrails.development/"
alias thrive="cd ~/Sites/thrive.development/thriveministry"
alias upcase="cd ~/Sites/upcase.trails"

# iMac
alias alongside="cd ~/Sites/alongside"
alias fixssh='eval $(ssh-agent) & ssh-add'
alias thriveimac="cd ~/Sites/thriveministry"

# Everday Stuff
alias ag='ag --path-to-ignore ~/.agignore'
alias copymysshkey='pbcopy < ~/.ssh/id_rsa.pub'
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias ds="cd ~/Sites"
alias gc="git commit -m"
alias gcache='git rm -r --cached .'
alias gclean='git remote prune origin'
alias gcommit="git commit"
alias gfix="git commit --amend"
alias gprune='git remote prune origin'
alias gpush="git push"
alias grebaselast="git rebase -i HEAD~"
alias grename="git branch -m"
alias gshortcuts='vi ~/.oh-my-zsh/plugins/git/git.plugin.zsh'
alias havingfun="osascript -e 'Set Volume 10' && say -v 'good news' it is time for lunch"
alias thrivedbdev='heroku pg:pull DATABASE_URL thriveministry_development --app thriveministry'
alias thrivedbtest='heroku pg:pull DATABASE_URL thriveministry_test --app thriveministry'
alias initialgit="g init && ga . && gc 'initial git'"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias mytheme="vim ~/.oh-my-zsh/themes"
alias pingit="ping google.com"
alias refresh='source ~/.zshrc'
alias searchfile='ack -g'
alias shortcuts='vi ~/.zshrc'
alias snippets='cd ~/.vim/bundle/vim-snippets/snippets'
alias sourcezshrc='source ~/.zshrc'
alias sourcevimrc='source ~/.vimrc'
alias starthttp='python3 -m http.server'
alias tellmeyoursecret='cat ~/.ssh/id_rsa.pub'
alias u='..'
alias uohmyzsh='upgrade_oh_my_zsh'
alias vimrc='vi ~/.vimrc'
alias vimrcbundles='vi ~/.vimrc.bundles'
alias whatismynetwork='ipconfig getifaddr en0'
alias whatismyip='curl ipecho.net/plain; echo'

# Bash
alias findstring='grep -rnw' 

# Docker
alias dockermachines='docker-machine ls'

# Heroku

alias addherokuremote='heroku git:remote -a'
alias herokuthrive='heroku apps --org thriveministry'
alias herokulunamisoo='heroku apps --org lunamisoo'
alias ha='heroku accounts'
alias haccountset='heroku accounts:set'
alias haddremote='heroku git:remote -a'
alias herokuelixir='heroku create --buildpack "https://github.com/HashNuke/heroku-buildpack-elixir.git"'
alias herokuphoenix='heroku buildpacks:add https://github.com/gjaldon/heroku-buildpack-phoenix-static.git'
alias hc='heroku create'
alias hcheck='curl https://status.heroku.com/api/v3/current-status.json'
alias hconfig='heroku config'
alias hconnectdemo='heroku addons:create herokuconnect:demo'
alias hconnectstatus='heroku connect:status -a thriveministry'
alias hconsole='heroku run rails console'
alias hdbm='heroku run rake db:migrate'
alias hhobbypostgres='heroku addons:create heroku-postgresql:hobby-dev'
alias hlocal='heroku local'
alias hlogin='heroku login'
alias hlogs='heroku logs --t'
alias hlogspg='heroku logs --tail --ps postgres --app thriveministry'
alias hlogsredis='heroku logs -p heroku-redis -t'
alias hlogsworker='heroku logs --ps worker'
alias hmon='heroku maintenance:on'
alias hmoff='heroku maintenance:off'
alias hmixectomigrate='heroku run mix ecto.migrate'
alias hopen='heroku open'
alias hproduction='git push production master'
alias hpush='git push heroku master'
alias hps='heroku ps'
alias hredis='heroku redis:info'
alias hstaging='git push staging master'
alias productionhmon='heroku maintenance:on --app'
alias productionhmoff='heroku maintenance:off --app'

# Jekyll
alias jserve='jekyll serve'

# NPM
alias npmis='npm install --save'
alias npmisd='npm install --save-dev'
alias npmbootstrap='npm install bootstrap'
alias npmgulp="sudo npm install -g gulp"
alias npmgulpl="npm install --save-dev gulp"
alias npmi="npm init"

# Elixir and Phoenix
alias mixdatabase='mix ecto.create && mix ecto.migrate'
alias mixnew='mix phoenix.new'
alias mixserver='mix phoenix.server'
alias mixdigest='mix phoenix.digest'
alias iexmix='iex -S mix'

# Jupyter
alias jnotebook='jupyter notebook'

# Pry
alias pryrails="pry -r ./config/environment"

# Rails
alias bi='bundle install'
alias binstallrspec='bin/rails generate rspec:install'
alias biwp='bundle install --without production'
alias brspec='bundle binstubs rspec-core'
alias be='bundle exec'
alias bu='bundle update'
alias checkgems='bundle-audit update'
alias installrspec='rails generate rspec:install'
alias rakecompile='RAILS_ENV=production bundle exec rake assets:precompile'
alias rakeclean='rake assets:clean'
alias rakehardclean='rake assets:clobber'
alias rcompile='RAILS_ENV=production bundle exec rake assets:precompile'
alias rreset='rake db:migrate:reset'
alias rmigrate='rake db:migrate'
alias rzero='rake db:migrate VERSION=0'
alias rstatus='rake db:migrate:status'
alias rst='rake db:migrate:status'
alias rrollback='rake db:rollback'
alias rr='rake routes'
alias rconsole='rails console --sandbox'
alias rd='rails destroy'
alias rdc='rails destroy controller'
alias rdm='rails destroy migration'
alias rds='rails destroy scaffold'
alias rg='rails generate'
alias rgc='rails generate controller'
alias rgm='rails generate migration'
alias rgs='rails generate scaffold'
alias rgrc="rails generate react:component"
alias rn='rails new'
alias rs='rails s'
alias sidekiq='bundle exec sidekiq'
alias taillogs='tail -f log/development.log'

# React
alias cra='create-react-app'

# React Native
alias rnativeios='react-native run-ios'
alias rnative='react-native'

# Redis
alias redis='redis-cli'
alias rediss='redis-server'

# Tmux Session Start
alias tmx="tmux new -s"
alias tmxc="vim ~/.tmux.conf"
alias tmxa="tmux attach"
alias tmxk='tmux kill-session -t'
alias tmxl="tmux ls"

# Tmuxinator
alias tmxn='tmuxinator new'
alias tmxo='tmuxinator open'
alias tmxs='tmuxinator start'
alias tmxthrive='tmuxinator start Thrive'

# Vagrant for Georgia Tech
alias vup='vagrant up'
alias vhalt='vagrant halt'
alias vssh='vagrant ssh'

# Yarn
alias yga='yarn global add'

# Exports
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
export TERM=xterm-256color

export GOPATH=$HOME/go
export PATH="$GOPATH/bin:$PATH"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"

export PATH=~/npm-global/bin:$PATH
export PATH="/usr/local/opt/qt@5.7/bin:$PATH"
source /Users/anthonylee/Sites/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
export PATH="/usr/local/opt/qt@5.5/bin:$PATH"

export PATH="$(brew --prefix)/bin:$PATH"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
