# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export EDITOR='vim'

ZSH_THEME="wild-cherry"

# Macbook Pro
alias anthonyleeio="cd ~/Sites/antwonlee.github.io"
alias ajl="cd ~/Sites/artandjustice/artandjustice"
alias dotfiles="cd ~/Sites/dotfiles"
alias gatech="cd ~/Documents/gatech"
alias gatechteam="cd ~/Documents/gatech/6300Spring15Team64/"
alias js="cd ~/Sites/javascript.development/"
alias kendo="cd ~/Sites/kendo"
alias playground="cd ~/Sites/playground"
alias ror="cd ~/Sites/rubyonrails.development/"
alias rubybox="cd ~/Sites/sandbox/rubybox"
alias sandbox="cd ~/Sites/sandbox"
alias swiftprojects="cd ~/Documents/swift"
alias thrive="cd ~/Sites/thrive/thriveministry"
alias thriveguestbook="cd ~/Sites/thrive/thriveguestbook"
alias tutorials="cd ~/Sites/tutorials"
alias upcase="cd ~/Sites/upcase.trails"
alias vimstars="cd ~/Sites/rubyonrails.development/vimstars"
alias ywamsalesforce="cd ~/Sites/rubyonrails.development/ywam-salesforce"

# Everday Stuff
alias copymysshkey='pbcopy < ~/.ssh/id_rsa.pub'
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias ds="cd ~/Sites"
alias gitshortcuts='vi ~/.oh-my-zsh/plugins/git/git.plugin.zsh'
alias gitcache='git rm -r --cached .'
alias gitprune='git remote prune origin'
alias gitclean='git remote prune origin'
alias havingfun="osascript -e 'Set Volume 10' && say -v 'good news' it is time for lunch"
alias thrivedatabasepulldev='heroku pg:pull DATABASE_URL thriveministry_development --app thriveministry'
alias thrivedatabasepulltest='heroku pg:pull DATABASE_URL thriveministry_test --app thriveministry'
alias initialgit="g init && ga . && gc 'initial git'"
alias mydotfiles='cd ~/Sites/dotfiles'
alias ohmyzsh="vim ~/.oh-my-zsh"
alias mytheme="vim ~/.oh-my-zsh/themes"
alias pingit="ping google.com"
alias shortcuts='vi ~/.zshrc'
alias sourcezshrc='source ~/.zshrc'
alias sourcevimrc='source ~/.vimrc'
alias tellmeyoursecret='cat ~/.ssh/id_rsa.pub'
alias u='..'
alias uohmyzsh='upgrade_oh_my_zsh'
alias vimrc='vi ~/.vimrc'
alias vimrcbundles='vi ~/.vimrc.bundles'
alias whatismynetwork='ipconfig getifaddr en0'
alias whatismyip='curl ipecho.net/plain; echo'

# Bower
alias bowerbootstrap="bower install bootstrap"

# Composer
alias coi='composer install'
alias cou='composer update'

# Foreman
alias fs='foreman start'

# Heroku
alias ha='heroku accounts'
alias haccountset='heroku accounts:set'
alias haddremote='heroku git:remote -a'
alias hc='heroku create'
alias hcheck='curl https://status.heroku.com/api/v3/current-status.json'
alias hconfig='heroku config'
alias hconnectdemo='heroku addons:create herokuconnect:demo'
alias hconnectstatus='heroku connect:status -a thriveministry'
alias hdbm='heroku run rake db:migrate'
alias hconsole='heroku run rails console'
alias hhobbypostgres='heroku addons:create heroku-postgresql:hobby-dev'
alias hlocal='heroku local'
alias hlogin='heroku login'
alias hlogs='heroku logs --t'
alias hlogspg='heroku logs --tail --ps postgres --app thriveministry'
alias hlogsredis='heroku logs -p heroku-redis -t'
alias hlogsworker='heroku logs --ps worker'
alias hpush='git push heroku master'
alias hmon='heroku maintenance:on'
alias hmoff='heroku maintenance:off'
alias hopen='heroku open'
alias hredis='heroku redis:info'
alias hps='heroku ps'

# Jekyll
alias jserve='jekyll serve'

# MySQL
alias mysqlstart="mysql.server start"
alias mysqlstop="mysql.server stop"

# NPM
alias npmbootstrap='npm install bootstrap'
alias npmgulp="sudo npm install -g gulp"
alias npmgulpl="npm install --save-dev gulp"
alias npmi="npm init"

# Rails
alias bi='bundle install'
alias binstallrspec='bin/rails generate rspec:install'
alias biwp='bundle install --without production'
alias brspec='bundle binstubs rspec-core'
alias bu='bundle update'
alias checkgems='bundle-audit update'
alias installrspec='rails generate rspec:install'
alias rakecompile='RAILS_ENV=production bundle exec rake assets:precompile'
alias rcompile='RAILS_ENV=production bundle exec rake assets:precompile'
alias rreset='rake db:migrate:reset'
alias rmigrate='rake db:migrate'
alias rzero='rake db:migrate VERSION=0'
alias rstatus='rake db:migrate:status'
alias rst='rake db:migrate:status'
alias rrollback='rake db:rollback'
alias rr='rake routes'
alias rconsole='rails console --sandbox'
alias rd='rails destroy'
alias rdc='rails destroy controller'
alias rdm='rails destroy migration'
alias rds='rails destroy scaffold'
alias rg='rails generate'
alias rgc='rails generate controller'
alias rgm='rails generate migration'
alias rgs='rails generate scaffold'
alias rn='rails new'
alias rs='rails s'
alias sidekiq='bundle exec sidekiq'
alias taillogs='tail -f log/development.log'

# Redis
alias redis='redis-cli'
alias rediss='redis-server'

# Sass
alias sw='sass --watch'

# Sails
alias sl='sails lift'
alias sn='sails new'

# Tmux Session Start
alias tmx="tmux new -s"
alias tmxc="vim ~/.tmux.conf"
alias tmxa="tmux attach"
alias tmxk='tmux kill-session -t'
alias tmxl="tmux ls"

# Tmuxinator
alias tmxn='tmuxinator new'
alias tmxo='tmuxinator open'
alias tmxs='tmuxinator start'
alias tmxthrive='tmuxinator start Thrive'

# Vagrant
alias vaprobash="curl -L http://bit.ly/vaprobash > Vagrantfile"
alias vd='vagrant destroy'
alias vh='vagrant halt'
alias vs='vagrant suspend'
alias vstatus='vagrant status'
alias vu='vagrant up'

# Yeoman
alias yoa="yo angular"

# User configuration
plugins=(git)
stty start undef
stty stop undef

source $ZSH/oh-my-zsh.sh
export TERM=xterm-256color

export PATH="$(brew --prefix)/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
# export PATH="/Users/anthonylee/.rbenv/shims:/Users/anthonylee/.rbenv/bin:/usr/local/opt/nvm/v0.10.33/bin:/Users/anthonylee/.bin:/Users/anthonylee/.rbenv/shims:/Users/anthonylee/.rbenv/bin:/Users/anthonylee/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/lib/node_modules:/usr/local/lib/node_modules"

export GOPATH=$HOME/go
export PATH="$GOPATH/bin:$PATH"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"

export PATH=~/npm-global/bin:$PATH

# setopt auto_cd
# cdpath=($HOME/ $HOME/src)

# docker
# eval "$(docker-machine env docker-vm)"
